// Dữ liệu biển báo giao thông Việt Nam
const trafficSigns = [
    { stt: 1, code: "P.101", name: "Đường cấm", type: "Biển báo cấm" },
    { stt: 2, code: "P.102", name: "Cấm đi ngược chiều", type: "Biển báo cấm" },
    { stt: 3, code: "P.103a", name: "Cấm xe ô tô", type: "Biển báo cấm" },
    { stt: 4, code: "P.103b", name: "Cấm xe ô tô rẽ phải", type: "Biển báo cấm" },
    { stt: 5, code: "P.103c", name: "Cấm xe ô tô rẽ trái", type: "Biển báo cấm" },
    { stt: 6, code: "P.104", name: "Cấm mô tô", type: "Biển báo cấm" },
    { stt: 7, code: "P.105", name: "Cấm xe ô tô và mô tô", type: "Biển báo cấm" },
    { stt: 8, code: "P.106a", name: "Cấm xe tải", type: "Biển báo cấm" },
    { stt: 9, code: "P.106b", name: "Cấm xe tải trên 2,5T", type: "Biển báo cấm" },
    { stt: 10, code: "P.106c", name: "Cấm xe tải chở hàng nguy hiểm", type: "Biển báo cấm" },
    { stt: 11, code: "P.107", name: "Cấm xe khách và xe tải", type: "Biển báo cấm" },
    { stt: 12, code: "P.107a", name: "Cấm xe khách", type: "Biển báo cấm" },
    { stt: 13, code: "P.107b", name: "Cấm xe taxi", type: "Biển báo cấm" },
    { stt: 14, code: "P.108", name: "Cấm xe kéo rơ-moóc", type: "Biển báo cấm" },
    { stt: 15, code: "P.109", name: "Cấm máy kéo", type: "Biển báo cấm" },
    { stt: 16, code: "P.110a", name: "Cấm xe đạp", type: "Biển báo cấm" },
    { stt: 17, code: "P.110b", name: "Cấm xe đạp thồ", type: "Biển báo cấm" },
    { stt: 18, code: "P.111a", name: "Cấm xe gắn máy", type: "Biển báo cấm" },
    { stt: 19, code: "P.111b", name: "Cấm xe lam", type: "Biển báo cấm" },
    { stt: 20, code: "P.111c", name: "Cấm xe lôi máy", type: "Biển báo cấm" },
    { stt: 21, code: "P.111d", name: "Cấm xe xích lô", type: "Biển báo cấm" },
    { stt: 22, code: "P.112", name: "Cấm người đi bộ", type: "Biển báo cấm" },
    { stt: 23, code: "P.113", name: "Cấm xe người kéo/đẩy", type: "Biển báo cấm" },
    { stt: 24, code: "P.114", name: "Cấm xe súc vật kéo", type: "Biển báo cấm" },
    { stt: 25, code: "P.115", name: "Hạn chế trọng lượng xe", type: "Biển báo cấm" },
    { stt: 26, code: "P.116", name: "Hạn chế trọng lượng trên trục xe", type: "Biển báo cấm" },
    { stt: 27, code: "P.117", name: "Hạn chế chiều cao xe", type: "Biển báo cấm" },
    { stt: 28, code: "P.118", name: "Hạn chế chiều ngang xe", type: "Biển báo cấm" },
    { stt: 29, code: "P.119", name: "Hạn chế chiều dài xe", type: "Biển báo cấm" },
    { stt: 30, code: "P.120", name: "Hạn chế chiều dài xe cơ giới kéo theo rơ-moóc hoặc sơ-mi rơ moóc", type: "Biển báo cấm" },
    { stt: 31, code: "P.121", name: "Cự ly tối thiểu giữa hai xe", type: "Biển báo cấm" },
    { stt: 32, code: "P.123a", name: "Cấm rẽ trái", type: "Biển báo cấm" },
    { stt: 33, code: "P.123b", name: "Cấm rẽ phải", type: "Biển báo cấm" },
    { stt: 34, code: "P.124a", name: "Cấm quay đầu xe", type: "Biển báo cấm" },
    { stt: 35, code: "P.124b", name: "Cấm xe ô tô quay đầu", type: "Biển báo cấm" },
    { stt: 36, code: "P.125", name: "Cấm vượt", type: "Biển báo cấm" },
    { stt: 37, code: "P.126", name: "Cấm xe tải vượt", type: "Biển báo cấm" },
    { stt: 38, code: "P.127", name: "Tốc độ tối đa cho phép", type: "Biển báo cấm" },
    { stt: 39, code: "P.127a", name: "Tốc độ tối đa cho phép vào ban đêm", type: "Biển báo cấm" },
    { stt: 40, code: "P.128", name: "Cấm sử dụng còi", type: "Biển báo cấm" },
    { stt: 41, code: "P.129", name: "Trạm thuế quan", type: "Biển báo cấm" },
    { stt: 42, code: "P.130", name: "Cấm dừng xe và đỗ xe", type: "Biển báo cấm" },
    { stt: 43, code: "P.131a", name: "Cấm đỗ xe", type: "Biển báo cấm" },
    { stt: 44, code: "P.131b", name: "Cấm đỗ xe ngày lẻ", type: "Biển báo cấm" },
    { stt: 45, code: "P.131c", name: "Cấm đỗ xe ngày chẵn", type: "Biển báo cấm" },
    { stt: 46, code: "P.132", name: "Nhường đường cho xe cơ giới đi ngược chiều qua đường hẹp", type: "Biển báo cấm" },
    { stt: 47, code: "DP.133", name: "Hết cấm vượt", type: "Biển báo cấm" },
    { stt: 48, code: "DP.134", name: "Hết hạn chế tốc độ tối đa", type: "Biển báo cấm" },
    { stt: 49, code: "DP.135", name: "Hết tất cả các lệnh cấm", type: "Biển báo cấm" },
    { stt: 50, code: "P.136", name: "Cấm đi thẳng", type: "Biển báo cấm" },
    { stt: 51, code: "P.137", name: "Cấm rẽ trái và rẽ phải", type: "Biển báo cấm" },
    { stt: 52, code: "P.138", name: "Cấm đi thẳng và rẽ trái", type: "Biển báo cấm" },
    { stt: 53, code: "P.139", name: "Cấm đi thẳng và rẽ phải", type: "Biển báo cấm" },
    { stt: 54, code: "P.140", name: "Cấm xe công nông và các loại xe tương tự", type: "Biển báo cấm" },
    { stt: 55, code: "W.201a", name: "Chỗ ngoặt nguy hiểm vòng bên trái", type: "Biển báo nguy hiểm" },
    { stt: 56, code: "W.201b", name: "Chỗ ngoặt nguy hiểm vòng bên phải", type: "Biển báo nguy hiểm" },
    { stt: 57, code: "W.201c", name: "Chỗ ngoặt nguy hiểm có nguy cơ lật xe bên phải", type: "Biển báo nguy hiểm" },
    { stt: 58, code: "W.201d", name: "Chỗ ngoặt nguy hiểm có nguy cơ lật xe bên trái", type: "Biển báo nguy hiểm" },
    { stt: 59, code: "W.202a", name: "Hai chỗ ngoặt ngược chiều nhau liên tiếp bên trái", type: "Biển báo nguy hiểm" },
    { stt: 60, code: "W.202b", name: "Hai chỗ ngoặt ngược chiều nhau liên tiếp bên phải", type: "Biển báo nguy hiểm" },
    { stt: 61, code: "W.203a", name: "Đường bị thu hẹp cả hai bên", type: "Biển báo nguy hiểm" },
    { stt: 62, code: "W.203b", name: "Đường bị thu hẹp bên trái", type: "Biển báo nguy hiểm" },
    { stt: 63, code: "W.203c", name: "Đường bị thu hẹp bên phải", type: "Biển báo nguy hiểm" },
    { stt: 64, code: "W.204", name: "Đường 2 chiều", type: "Biển báo nguy hiểm" },
    { stt: 65, code: "W.205a", name: "Đường giao nhau", type: "Biển báo nguy hiểm" },
    { stt: 66, code: "W.205b", name: "Đường giao nhau", type: "Biển báo nguy hiểm" },
    { stt: 67, code: "W.205c", name: "Đường giao nhau", type: "Biển báo nguy hiểm" },
    { stt: 68, code: "W.205d", name: "Đường giao nhau", type: "Biển báo nguy hiểm" },
    { stt: 69, code: "W.205e", name: "Đường giao nhau", type: "Biển báo nguy hiểm" },
    { stt: 70, code: "W.206", name: "Đường giao nhau chạy theo vòng xuyến", type: "Biển báo nguy hiểm" },
    { stt: 71, code: "W.207a", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 72, code: "W.207b", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 73, code: "W.207c", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 74, code: "W.207d", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 75, code: "W.207e", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 76, code: "W.207f", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 77, code: "W.207g", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 78, code: "W.207h", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 79, code: "W.207i", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 80, code: "W.207k", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 81, code: "W.207l", name: "Giao nhau với đường không ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 82, code: "W.208", name: "Giao nhau với đường ưu tiên", type: "Biển báo nguy hiểm" },
    { stt: 83, code: "W.209", name: "Giao nhau có tín hiệu đèn", type: "Biển báo nguy hiểm" },
    { stt: 84, code: "W.210", name: "Giao nhau với đường sắt có rào chắn", type: "Biển báo nguy hiểm" },
    { stt: 85, code: "W.211a", name: "Giao nhau với đường sắt không có rào chắn", type: "Biển báo nguy hiểm" },
    { stt: 86, code: "W.211b", name: "Giao nhau cùng mức với đường tàu điện", type: "Biển báo nguy hiểm" },
    { stt: 87, code: "W.212", name: "Cầu hẹp", type: "Biển báo nguy hiểm" },
    { stt: 88, code: "W.213", name: "Cầu tạm", type: "Biển báo nguy hiểm" },
    { stt: 89, code: "W.214", name: "Cầu xoay – cầu cất", type: "Biển báo nguy hiểm" },
    { stt: 90, code: "W.215a", name: "Kè – vực sâu phía trước", type: "Biển báo nguy hiểm" },
    { stt: 91, code: "W.215b", name: "Kè – vực sâu phía trước", type: "Biển báo nguy hiểm" },
    { stt: 92, code: "W.215c", name: "Kè – vực sâu phía trước", type: "Biển báo nguy hiểm" },
    { stt: 93, code: "W.216a", name: "Đường ngầm", type: "Biển báo nguy hiểm" },
    { stt: 94, code: "W.216b", name: "Đường ngầm có nguy cơ lũ quét", type: "Biển báo nguy hiểm" },
    { stt: 95, code: "W.217", name: "Bến phà", type: "Biển báo nguy hiểm" },
    { stt: 96, code: "W.218", name: "Cửa chui", type: "Biển báo nguy hiểm" },
    { stt: 97, code: "W.219", name: "Dốc xuống nguy hiểm", type: "Biển báo nguy hiểm" },
    { stt: 98, code: "W.220", name: "Dốc lên nguy hiểm", type: "Biển báo nguy hiểm" },
    { stt: 99, code: "W.221a", name: "Đường không bằng phẳng", type: "Biển báo nguy hiểm" },
    { stt: 100, code: "W.221b", name: "Đường không bằng phẳng", type: "Biển báo nguy hiểm" },
    { stt: 101, code: "W.222a", name: "Đường trơn", type: "Biển báo nguy hiểm" },
    { stt: 102, code: "W.222b", name: "Lề nguy hiểm", type: "Biển báo nguy hiểm" },
    { stt: 103, code: "W.223a", name: "Vách núi nguy hiểm", type: "Biển báo nguy hiểm" },
    { stt: 104, code: "W.223b", name: "Vách núi nguy hiểm", type: "Biển báo nguy hiểm" },
    { stt: 105, code: "W.224", name: "Đường dành cho người đi bộ cắt ngang", type: "Biển báo nguy hiểm" },
    { stt: 106, code: "W.225", name: "Trẻ em", type: "Biển báo nguy hiểm" },
    { stt: 107, code: "W.226", name: "Đường người đi xe đạp cắt ngang", type: "Biển báo nguy hiểm" },
    { stt: 108, code: "W.227", name: "Công trường", type: "Biển báo nguy hiểm" },
    { stt: 109, code: "W.228a", name: "Đá lở", type: "Biển báo nguy hiểm" },
    { stt: 110, code: "W.228b", name: "Đá lở", type: "Biển báo nguy hiểm" },
    { stt: 111, code: "W.228c", name: "Sỏi đá bắn lên", type: "Biển báo nguy hiểm" },
    { stt: 112, code: "W.228d", name: "Nền đường yếu", type: "Biển báo nguy hiểm" },
    { stt: 113, code: "W.229", name: "Dải máy bay lên xuống", type: "Biển báo nguy hiểm" },
    { stt: 114, code: "W.230", name: "Gia súc", type: "Biển báo nguy hiểm" },
    { stt: 115, code: "W.231", name: "Thú rừng vượt qua đường", type: "Biển báo nguy hiểm" },
    { stt: 116, code: "W.232", name: "Gió ngang", type: "Biển báo nguy hiểm" },
    { stt: 117, code: "W.233", name: "Nguy hiểm khác", type: "Biển báo nguy hiểm" },
    { stt: 118, code: "W.234", name: "Giao nhau với đường 2 chiều", type: "Biển báo nguy hiểm" },
    { stt: 119, code: "W.235", name: "Đường đôi", type: "Biển báo nguy hiểm" },
    { stt: 120, code: "W.236", name: "Hết đường đôi", type: "Biển báo nguy hiểm" },
    { stt: 121, code: "W.237", name: "Cầu vòng", type: "Biển báo nguy hiểm" },
    { stt: 122, code: "W.238", name: "Đường cao tốc phía trước", type: "Biển báo nguy hiểm" },
    { stt: 123, code: "W.239a", name: "Đường cáp điện ở phía trên", type: "Biển báo nguy hiểm" },
    { stt: 124, code: "W.239b", name: "Chiều cao an toàn", type: "Biển báo nguy hiểm" },
    { stt: 125, code: "W.240", name: "Đường hầm", type: "Biển báo nguy hiểm" },
    { stt: 126, code: "W.241", name: "Ùn tắc giao thông", type: "Biển báo nguy hiểm" },
    { stt: 127, code: "W.243a", name: "Nơi đường sắt giao không vuông góc với đường bộ", type: "Biển báo nguy hiểm" },
    { stt: 128, code: "W.243b", name: "Nơi đường sắt giao không vuông góc với đường bộ", type: "Biển báo nguy hiểm" },
    { stt: 129, code: "W.243c", name: "Nơi đường sắt giao không vuông góc với đường bộ", type: "Biển báo nguy hiểm" },
    { stt: 130, code: "W.244", name: "Đoạn đường hay xảy ra tai nạn", type: "Biển báo nguy hiểm" },
    { stt: 131, code: "W.245a", name: "Đi chậm", type: "Biển báo nguy hiểm" },
    { stt: 132, code: "W.246a", name: "Chú ý chướng ngại vật – Vòng tránh ra hai bên", type: "Biển báo nguy hiểm" },
    { stt: 133, code: "W.246b", name: "Chú ý chướng ngại vật – Vòng tránh sang bên trái", type: "Biển báo nguy hiểm" },
    { stt: 134, code: "W.246c", name: "Chú ý chướng ngại vật – Vòng tránh sang bên phải", type: "Biển báo nguy hiểm" },
    { stt: 135, code: "W.247", name: "Chú ý xe đỗ", type: "Biển báo nguy hiểm" },
    { stt: 136, code: "R.122", name: "Dừng lại", type: "Biển hiệu lệnh" },
    { stt: 137, code: "R.301a", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 138, code: "R.301b", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 139, code: "R.301c", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 140, code: "R.301d", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 141, code: "R.301e", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 142, code: "R.301f", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 143, code: "R.301g", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 144, code: "R.301h", name: "Hướng đi phải theo", type: "Biển hiệu lệnh" },
    { stt: 145, code: "R.302a", name: "Hướng phải đi vòng chướng ngại vật", type: "Biển hiệu lệnh" },
    { stt: 146, code: "R.302b", name: "Hướng phải đi vòng chướng ngại vật", type: "Biển hiệu lệnh" },
    { stt: 147, code: "R.302c", name: "Hướng phải đi vòng chướng ngại vật", type: "Biển hiệu lệnh" },
    { stt: 148, code: "R.303", name: "Nơi giao nhau chạy theo vòng xuyến", type: "Biển hiệu lệnh" },
    { stt: 149, code: "R.304", name: "Đường dành cho xe thô sơ", type: "Biển hiệu lệnh" },
    { stt: 150, code: "R.305", name: "Đường dành cho người đi bộ", type: "Biển hiệu lệnh" },
    { stt: 151, code: "R.306", name: "Tốc độ tối thiểu cho phép", type: "Biển hiệu lệnh" },
    { stt: 152, code: "R.307", name: "Hết tốc độ tối thiểu", type: "Biển hiệu lệnh" },
    { stt: 153, code: "R.308a", name: "Tuyến đường cầu vượt cắt qua", type: "Biển hiệu lệnh" },
    { stt: 154, code: "R.308b", name: "Tuyến đường cầu vượt cắt qua", type: "Biển hiệu lệnh" },
    { stt: 155, code: "R.309", name: "Ấn còi", type: "Biển hiệu lệnh" },
    { stt: 156, code: "R.310a", name: "Hướng đi phải theo cho các xe chở hàng nguy hiểm", type: "Biển hiệu lệnh" },
    { stt: 157, code: "R.310b", name: "Hướng đi phải theo cho các xe chở hàng nguy hiểm", type: "Biển hiệu lệnh" },
    { stt: 158, code: "R.310c", name: "Hướng đi phải theo cho các xe chở hàng nguy hiểm", type: "Biển hiệu lệnh" },
    { stt: 159, code: "R.403a", name: "Đường dành cho xe ô tô", type: "Biển hiệu lệnh" },
    { stt: 160, code: "R.403b", name: "Đường dành cho xe ô tô, xe máy", type: "Biển hiệu lệnh" },
    { stt: 161, code: "R.403c", name: "Đường dành cho xe buýt", type: "Biển hiệu lệnh" },
    { stt: 162, code: "R.403d", name: "Đường dành cho xe ô tô con", type: "Biển hiệu lệnh" },
    { stt: 163, code: "R.403e", name: "Đường dành cho xe máy", type: "Biển hiệu lệnh" },
    { stt: 164, code: "R.403f", name: "Đường dành cho xe máy và xe đạp", type: "Biển hiệu lệnh" },
    { stt: 165, code: "R.404a", name: "Hết đoạn đường dành cho xe ô tô", type: "Biển hiệu lệnh" },
    { stt: 166, code: "R.404b", name: "Hết đoạn đường dành cho xe ô tô, xe máy", type: "Biển hiệu lệnh" },
    { stt: 167, code: "R.404c", name: "Hết đoạn đường dành cho xe buýt", type: "Biển hiệu lệnh" },
    { stt: 168, code: "R.404d", name: "Hết đoạn đường dành cho xe ô tô con", type: "Biển hiệu lệnh" },
    { stt: 169, code: "R.404e", name: "Hết đoạn đường dành cho xe máy", type: "Biển hiệu lệnh" },
    { stt: 170, code: "R.404f", name: "Hết đoạn đường dành cho xe máy và xe đạp", type: "Biển hiệu lệnh" },
    { stt: 171, code: "R.411", name: "Hướng đi trên mỗi làn đường phải theo", type: "Biển hiệu lệnh" },
    { stt: 172, code: "R.412a", name: "Làn đường dành cho xe ô tô khách", type: "Biển hiệu lệnh" },
    { stt: 173, code: "R.412b", name: "Làn đường dành cho xe ô tô con", type: "Biển hiệu lệnh" },
    { stt: 174, code: "R.412c", name: "Làn đường dành cho xe ô tô tải", type: "Biển hiệu lệnh" },
    { stt: 175, code: "R.412d", name: "Làn đường dành cho xe máy", type: "Biển hiệu lệnh" },
    { stt: 176, code: "R.412e", name: "Làn đường dành cho xe buýt", type: "Biển hiệu lệnh" },
    { stt: 177, code: "R.412f", name: "Làn đường dành cho xe ô tô", type: "Biển hiệu lệnh" },
    { stt: 178, code: "R.412g", name: "Làn đường dành cho xe máy và xe đạp", type: "Biển hiệu lệnh" },
    { stt: 179, code: "R.412i", name: "Kết thúc làn đường dành cho xe ô tô khách", type: "Biển hiệu lệnh" },
    { stt: 180, code: "R.412j", name: "Kết thúc làn đường dành cho xe ô tô con", type: "Biển hiệu lệnh" },
    { stt: 181, code: "R.412k", name: "Kết thúc làn đường dành cho xe ô tô tải", type: "Biển hiệu lệnh" },
    { stt: 182, code: "R.412l", name: "Kết thúc làn đường dành cho xe máy", type: "Biển hiệu lệnh" },
    { stt: 183, code: "R.412m", name: "Kết thúc làn đường dành cho xe buýt", type: "Biển hiệu lệnh" },
    { stt: 184, code: "R.412n", name: "Kết thúc làn đường dành cho xe ô tô", type: "Biển hiệu lệnh" },
    { stt: 185, code: "R.412o", name: "Kết thúc làn đường dành cho xe máy và xe đạp", type: "Biển hiệu lệnh" },
    { stt: 186, code: "R.415a", name: "Phân làn", type: "Biển hiệu lệnh" },
    { stt: 187, code: "R.415b", name: "Hết phân làn", type: "Biển hiệu lệnh" },
    { stt: 188, code: "R.420", name: "Bắt đầu khu đông dân cư", type: "Biển hiệu lệnh" },
    { stt: 189, code: "R.421", name: "Hết khu đông dân cư", type: "Biển hiệu lệnh" },
    { stt: 190, code: "R.E,9a", name: "Cấm đỗ xe trong khu vực", type: "Biển hiệu lệnh" },
    { stt: 191, code: "R.E,9b", name: "Cấm đỗ xe theo giờ trong khu vực", type: "Biển hiệu lệnh" },
    { stt: 192, code: "R.E,9c", name: "Khu vực đỗ xe", type: "Biển hiệu lệnh" },
    { stt: 193, code: "R.E,9d", name: "Tốc độ tối đa trong khu vực", type: "Biển hiệu lệnh" },
    { stt: 194, code: "R.E,11a", name: "Đường hầm", type: "Biển hiệu lệnh" },
    { stt: 195, code: "R.E,11b", name: "Kết thúc đường hầm", type: "Biển hiệu lệnh" },
    { stt: 196, code: "I.401", name: "Bắt đầu đường ưu tiên", type: "Biển chỉ dẫn" },
    { stt: 197, code: "I.402", name: "Hết đoạn đường ưu tiên", type: "Biển chỉ dẫn" },
    { stt: 198, code: "I.405a", name: "Đường cụt", type: "Biển chỉ dẫn" },
    { stt: 199, code: "I.405b", name: "Đường cụt", type: "Biển chỉ dẫn" },
    { stt: 200, code: "I.405c", name: "Đường cụt", type: "Biển chỉ dẫn" },
    { stt: 201, code: "I.406", name: "Được ưu tiên qua đường hẹp", type: "Biển chỉ dẫn" },
    { stt: 202, code: "I.407a", name: "Đường một chiều", type: "Biển chỉ dẫn" },
    { stt: 203, code: "I.407b", name: "Đường một chiều", type: "Biển chỉ dẫn" },
    { stt: 204, code: "I.407c", name: "Đường một chiều", type: "Biển chỉ dẫn" },
    { stt: 205, code: "I.408", name: "Nơi đỗ xe", type: "Biển chỉ dẫn" },
    { stt: 206, code: "I.408a", name: "Nơi đỗ xe một phần trên hè phố", type: "Biển chỉ dẫn" },
    { stt: 207, code: "I.409", name: "Chỗ quay xe", type: "Biển chỉ dẫn" },
    { stt: 208, code: "I.410", name: "Khu vực quay xe", type: "Biển chỉ dẫn" },
    { stt: 209, code: "I.416", name: "Đường tránh", type: "Biển chỉ dẫn" },
    { stt: 210, code: "I.418", name: "Lối đi ở những vị trí cấm rẽ", type: "Biển chỉ dẫn" },
    { stt: 211, code: "I.423a", name: "Vị trí người đi bộ sang ngang", type: "Biển chỉ dẫn" },
    { stt: 212, code: "I.423b", name: "Vị trí người đi bộ sang ngang", type: "Biển chỉ dẫn" },
    { stt: 213, code: "I.423c", name: "Điểm bắt đầu đường đi bộ", type: "Biển chỉ dẫn" },
    { stt: 214, code: "I.424a", name: "Cầu vượt qua đường cho người đi bộ", type: "Biển chỉ dẫn" },
    { stt: 215, code: "I.424b", name: "Cầu vượt qua đường cho người đi bộ", type: "Biển chỉ dẫn" },
    { stt: 216, code: "I.424c", name: "Hầm chui qua đường cho người đi bộ", type: "Biển chỉ dẫn" },
    { stt: 217, code: "I.424d", name: "Hầm chui qua đường cho người đi bộ", type: "Biển chỉ dẫn" },
];


// Thống kê số lượng theo loại biển
function getSignStatistics() {
    const stats = {};
    trafficSigns.forEach(sign => {
        if (!stats[sign.type]) {
            stats[sign.type] = 0;
        }
        stats[sign.type]++;
    });
    return stats;
}

// Tìm kiếm biển báo
function searchSigns(keyword) {
    const lowerKeyword = keyword.toLowerCase();
    return trafficSigns.filter(sign =>
        sign.name.toLowerCase().includes(lowerKeyword) ||
        sign.code.toLowerCase().includes(lowerKeyword)
    );
}

// Lấy biển báo theo loại
function getSignsByType(type) {
    return trafficSigns.filter(sign => sign.type === type);
}
